name: pad - Guides, resources, notes, docs and knowledge for everything Oscar.
sass:
  style: compressed
prose: 
  rooturl: "_docs"
  siteurl: "http://pad.oscarb.se"
markdown: kramdown
kramdown:
  toc_levels: 2..3
  hard_wrap: true
  auto_id_stripping: true
  auto_ids: true
gems:
  - jekyll-mentions
collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      permalink: "/:slug"

