name: pad - Guides, resources, notes, docs and knowledge for everything Oscar.
sass:
  style: compressed
markdown: kramdown
kramdown:
  toc_levels: 1..2
  hard_wrap: true
  auto_id_stripping: true
  auto_ids: true
collections:
- docs
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "docs"
    values:
      permalink: "/:basename"
    
