name: pad - Guides, resources, notes, docs and knowledge for everything Oscar.
sass:
  style: compressed
markdown: kramdown
kramdown:
  toc_levels: 1..2
  hard_wrap: true
  auto_id_stripping: true
  auto_ids: true
collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      permalink: "/:title"

    
